### ISSUE TITLE
run-s command

### ISSUE THREAD

**Issue by bilalesi** [AgoraIO-Community/agora-rtc-react#1]
i start using the package, and honestly, i found it great and very helpful, but the thing is you are using npm-run-all and with shortcut of run-s in package-json, and this is make it very difficult to install the package in cloud server such as heroku, so when i run the deployement process in Heroku, i got this error 
```
 npm ERR! > agora-rtc-react@1.0.1 prepare
remote:        npm ERR! > run-s build
remote:        npm ERR! sh: 1: run-s: not found
```
so please can you make the package build simply by npm due there is no need to use npm-run-all for the moment as i see the implementation,

**Comment by EkaanshArora** [comment]
Can you describe the steps to reproduce the problem? 
I used the example code from the repo in a new CRA project with the wrapper installed. I was able to build the project on Heroku without any errors. Otherwise you can always build locally `npm run build` and upload the build.

**Comment by EkaanshArora** [comment]
If you're getting node out of memory error during CRA build, you can set the config using this terminal command `heroku config:set NODE_OPTIONS="--max_old_space_size=2560" -a <appName>`
