### ISSUE TITLE
Please cover an example featuring screen sharing

### ISSUE THREAD

**Issue by Harikrishnan19** [AgoraIO-Community/Agora-RTC-React#10]

**Comment by diegoaguilar** [comment]
Hey @Harikrishnan19 any findings so far?

**Comment by Harikrishnan19** [comment]
I found no snippet of screen share implementation using agora rtc react. But I managed to do that by using agora-rtc-sdk-ng. I couldn't able to use their hooks directly as are immediately called after initialization.

import AgoraRTC from "agora-rtc-sdk-ng";

const [screenShareClient, setScreenShareClient] = useState(null)
const [screenVideoTrack, setScreenVideoTrack] = useState(null)

// to listen when stop sharing is clicked by user
useEffect(() => {
    if (screenVideoTrack) {
      screenVideoTrack.on('track-ended', async () => {
        await handleScreenShareStop()
      })
    }
  },[screenVideoTrack])

// to start screen sharing
async function handleScreenShareStart() {
    const screenClient = AgoraRTC.createClient(config);
    await screenClient.join(appId, channelName, token, null);
    const screenTrack = await AgoraRTC.createScreenVideoTrack();
    await screenClient.publish(screenTrack);
    setScreenShareClient(screenClient)
    setScreenVideoTrack(screenTrack)
  }

// to stop screen sharing
  async function handleScreenShareStop() {
    screenVideoTrack.close();
    await screenShareClient.leave();
    setScreenVideoTrack(null)
    setScreenShareClient(null)
  }

  // make sure to stop screen sharing when the user leaves.
  You could also refer [Agora rtc sdk ng documentation for screen-sharing](https://agoraio-community.github.io/AgoraWebSDK-NG/docs/en/screensharing)

**Comment by EkaanshArora** [comment]
I'm updating the wrapper with #7 soon I'll try and add a screenshare example as well. Thanks for the feedback.
