### ISSUE TITLE
associating user with video

### ISSUE THREAD

**Issue by brismol** [AgoraIO-Community/agora-rtc-react#14]
I'm a student trying with my team to build a video chat app with support for a simple game. We need to divide the users into two teams and sort them on the screen. We can't figure out a way for the callers to identify themself so that we can associate it with our user models. Please help if you can! Any advice would be super appreciated!

**Comment by EkaanshArora** [comment]
Hey you can use [Agora RTM](https://docs.agora.io/en/Real-time-Messaging/product_rtm?platform=Web) to signal users and their screenshare UIDs to other users in the channel. You can send messages with a user's UID and their screenshare UID along with their team name etc.
Or a simpler hack would be to have some logic where you assign a particular UID to a user's screenshare, for example: User A has UID 1000, User's A screenshare is always set to 1001. That way you can associate screenshare with other users. But be sure to avoid any UID collisions, maybe use the timestamp to generate UIDs.
Hope this helps.

**Comment by brismol** [comment]
Thanks so much!!! This helps a ton! You’re the best!


Sent from Yahoo Mail for iPhone


On Friday, October 1, 2021, 7:51 AM, Ekaansh Arora ***@***.***> wrote:




Hey you can use Agora RTM to signal users and their screenshare UIDs to other users in the channel. You can send messages with a user's UID and their screenshare UID along with their team name etc.
Or a simpler hack would be to have some logic where you assign a particular UID to a user's screenshare, for example: User A has UID 1000, User's A screenshare is always set to 1001. That way you can associate screenshare with other users. But be sure to avoid any UID collisions, maybe use the timestamp to generate UIDs.
Hope this helps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
