### ISSUE TITLE
How to know who is joined?

### ISSUE THREAD

**Issue by kumaramitbag** [AgoraIO-Community/agora-rtc-react#16]
Hi. I am new with agora. Please help me.
Suppose 2 users Asit and Sumit is joining the channel via web browser. How Asit will knows who is joined similar way how sumit will knows who is joined in this call? Please tell me how to set the joiner name?

And also one thing i want to know when any user mute his video in the opposite end how to know user is on the call or leave from call. because after video mute videotrack is removed and that's why only one user is showing. Please help me.

**Comment by jonah-katz** [comment]
@EkaanshArora slack channel still active?
