### ISSUE TITLE
How to share the group call directly to Youtube Stream?

### ISSUE THREAD

**Issue by kamal-hossain** [AgoraIO-Community/agora-rtc-react#17]
I have tried to follow [this](https://docs.agora.io/en/Interactive%20Broadcast/cdn_streaming_web?platform=Web#sample-code) example. But sadly it is telling nothing about exact instruction for Youtube stream.

I also tried to implement some of [this](https://docs.agora.io/en/Video/API%20Reference/web_ng/interfaces/iagorartcclient.html#setlivetranscoding) methods on **client** but getting error. Not working at all.

Can anyone give me any straight forward exmple to pass the group call stream directly to Youtube stream?

**Comment by EkaanshArora** [comment]
@kamal-hossain you can follow these steps:
```js
let LiveTranscoding = {} // you need to create the transcoding config
client.setLiveTranscoding(LiveTranscoding); // set the config
client.startLiveStreaming("rtmp://a.rtmp.youtube.com/livexxxxxxxxxxxxxxxx", true) // add your rtmp url for YouTube
// your stream should appear on youtube in a couple seconds if your config is correct 


// when you want to update the transcoding config
client.setLiveTranscoding(newConfig);
// when you want to stop
client.stopLiveStreaming("your RTMP URL")
```
For an example config you can view the [doc](https://docs.agora.io/en/Interactive%20Broadcast/cdn_streaming_web?platform=Web#sample-code). Make sure your remote UIDs are correct.

If you need more help, please join our community [slack](https://www.agora.io/en/join-slack).
