### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by iddan** [AgoraIO-Community/agora-rtc-react#2]
It would be preferable if the package would be deployed to npm instead of installed through git.

**Comment by adnux** [comment]
I'm having problems to install the dependency and deploy it on GCP.
It shows some error related to corejs, but removing the `agora-rtc-react` made it work!
Please publish it!

**Comment by boy51** [comment]
Yeah I just went ahead and did it so now `npm i agora-rtc-react` should work

**Comment by EkaanshArora** [comment]
@boy51 can you share the NPM package access with me? We can officially maintain it and release updates to NPM.
