### ISSUE TITLE
Disable mic on connect

### ISSUE THREAD

**Issue by lil12t** [AgoraIO-Community/agora-rtc-react#20]
How can I use example below in order to connect without microphone enabled ? As far as I know, we can't call hooks conditionally

```tsx import React from "react";
import { AgoraVideoPlayer, createClient, createMicrophoneAndCameraTracks } from "agora-rtc-react";

const config = {mode: "rtc", codec: "vp8"}

const useClient = createClient(config);
const useMicrophone = createMicrophoneAudioTrack();

const App = () => {
  const client = useClient();
  const { ready, tracks } = useMicrophone(); // it should be muted by default and enabled when user click mic icon

  return (
    ready && <Player />
  )
}

**Comment by EkaanshArora** [comment]
You can just use the [setEnabled](https://docs.agora.io/en/Voice/API%20Reference/web_ng/interfaces/ilocaltrack.html#setenabled) method on the track to disable it on first render - `tracks.setEnabled(false)`
(by using the useEffect hook for example)
