### ISSUE TITLE
Enable setLogLevel

### ISSUE THREAD

**Issue by mikeeus** [AgoraIO-Community/Agora-RTC-React#22]
Right now the logLevel defaults to DEBUG which floods the console with messages.
Exporting the setLogLevel function would let us customize determine the level we want when developing.

**Comment by EkaanshArora** [comment]
Hi @mikeeus thanks for the PR. We already have a default export for AgoraRTC. We'd expect users to set the log level like so:
```jsx
import AgoraRTC, {createClient} from "agora-rtc-react";
...
AgoraRTC.setLogLevel(3)
```
Does that solve your issue?

**Comment by mikeeus** [comment]
Yes that should work, thanks!

**Comment by talksik** [comment]
Anyone kn ow why I get this error when trying to build in production? `Attempted import error: 'agora-rtc-sdk-ng' does not contain a default export (imported as 'AgoraRTC__default').`
