### ISSUE TITLE
Please remove api.md and example.md

### ISSUE THREAD

**Issue by ncaq** [AgoraIO-Community/Agora-RTC-React#27]
I search videoPlayerConfig.

I found it in Wiki Page.
[API · AgoraIO-Community/Agora-RTC-React Wiki](https://github.com/AgoraIO-Community/Agora-RTC-React/wiki/API)

However, Do not exist in repo Markdown.
[Agora-RTC-React/api.md at master · AgoraIO-Community/Agora-RTC-React](https://github.com/AgoraIO-Community/Agora-RTC-React/blob/master/api.md)

The existence of a manual that has not been updated is a source of confusion.
So I think we should remove the manuals from the repository and direct people to the Wiki only.

**Comment by EkaanshArora** [comment]
Sorry about the confusion, removed.
