### ISSUE TITLE
setLogLevel

### ISSUE THREAD

**Issue by emorling** [AgoraIO-Community/agora-rtc-react#3]
How can I set the log level using this? Equivalent to:

AgoraRTC.Logger.setLogLevel(AgoraRTC.Logger.INFO);

**Comment by EkaanshArora** [comment]
You can do this:
```jsx
// the wrapper exports the AgoraRTC class from the SDK
import AgoraRTC from 'agora-rtc-react';

// set log level - for example
AgoraRTC.setLogLevel(1);
```
More info here - https://docs.agora.io/en/Video/API%20Reference/web_ng/interfaces/iagorartc.html#setloglevel
