### ISSUE TITLE
client.leave() will not trigger "user-left" on other clients

### ISSUE THREAD

**Issue by emorling** [AgoraIO-Community/agora-rtc-react#4]
When leaving a channel the "user-left" event is not triggered on other clients:

`
const doLeave = useCallback(async () => {
    console.log("leaving");
    await client.leave();
    client.removeAllListeners();
    tracks[0].close();
    tracks[1].close();
  }, [client, tracks]);
`

However, reloading the window on the leaver does trigger "user-left" on other clients

**Comment by EkaanshArora** [comment]
Does the leave method get called successfully? Can you provide an example to reproduce the issue?

**Comment by wevertoum** [comment]
same problem here...
