### ISSUE TITLE
screen sharing not working on safari browser

### ISSUE THREAD

**Issue by garimalande20** [AgoraIO-Community/Agora-RTC-React#41]
we are not able to share screen for safari browser.
 I was getting an error "AgoraRTCError UNEXPECTED_ERROR: InvalidAccessError: getDisplayMedia must be called from a user gesture handler."

Can you please provide some code snippets for resolving this issue.

**Comment by Migggz** [comment]
@garimalande20 which version of Safari do you use?

**Comment by garimalande20** [comment]
@Migggz Safari Version : 15.4 (17613.1.17.1.13)

**Comment by EkaanshArora** [comment]
Are you using safari on a mobile device?

**Comment by garimalande20** [comment]
on mac (desktop) web device.
