### ISSUE TITLE
Audio track does not stop in Chrome Icognito

### ISSUE THREAD

**Issue by emorling** [AgoraIO-Community/agora-rtc-react#5]
When leaving a channel  in an Incognito Window in chrome the audio is still on.

`
const doLeave = useCallback(async () => {
    console.log("leaving");
    await client.leave();
    client.removeAllListeners();
    tracks[0].close();
    tracks[1].close();
  }, [client, tracks]);
`

**Comment by emorling** [comment]
This issue also exists when running in Safari, without incognito.

**Comment by EkaanshArora** [comment]
Can you provide a minimum reproducible example using the wrapper?
