### ISSUE TITLE
Audio is working only on refresh 

### ISSUE THREAD

**Issue by gosrinin** [AgoraIO-Community/agora-rtc-react#6]
Lets assume 2 users A and B is joining the channel via web browser User "A" is able to hear and see User "B" where as User "B" is able to see User "A" but unable to hear user "A" ideally only one participant is able hear and see where as the other participant is able to only see and not able to hear if the participant who is unable to hear refresh his browser then everything is working fine.

Checked the audio profile its automatically assigned by agora and we don't have anything to do there and this happens in the AgoraWeb-React

SDK Version 3.6

**Comment by EkaanshArora** [comment]
Are you facing the error you mentioned with this repo or AgoraWeb-React?

**Comment by gosrinin** [comment]
this is with respect to Agoraweb react still we are facing this issue with IOS

**Comment by EkaanshArora** [comment]
AgoraWeb-React is a separate repo with a completely different codebase, please open the issue there.
