### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by DeepakSaini119** [AgoraIO-Community/agora-rtc-react#8]
Hi, I followed [the tutorial](https://www.agora.io/en/blog/building-a-video-chat-app-using-react-hooks-and-agora/) from here. Except, according to [this SO question](https://stackoverflow.com/questions/64560370/getting-can-not-get-gateway-server-exception-on-joining-a-call), token based authentication is mandatory now. I enabled that by generating a token and giving the value(instead of null), but I still get the error:
```
Access to XMLHttpRequest at 'https://cds-ap-web-3.agora.io/api/v1?action=config' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```
Am I missing something. TIA.

**Comment by EkaanshArora** [comment]
Hey @DeepakSaini119 this isn't a problem with this repo. You're getting CORS because you're trying to access the token from your localhost over HTTP. I'd recommend trying the same code with HTTPS instead.
