### ISSUE TITLE
Video gets cropped

### ISSUE THREAD

**Issue by 123vivekr** [AgoraIO-Community/agora-rtc-react#9]
The video gets cropped for different window sizes:

For a wide window:
![a](https://user-images.githubusercontent.com/28249428/130311003-07bbf1df-a093-40a2-8b01-470f7a0dbdbe.jpg)

For a narrower window:
![b](https://user-images.githubusercontent.com/28249428/130311012-35a0fda7-82b3-480a-9348-0014128fe925.jpg)

I have used the same code snippet from the examples. 

In this case, the user can see different parts of the stream depending on their window sizes. How do I resolve this?

**Comment by EkaanshArora** [comment]
You can use CSS to override the behavior using `object-fit: "contain"` targeting the element containing the video. I'll review and try adding a prop to the AgoraVideoPlayer component to make it easier in the future.

**Comment by EkaanshArora** [comment]
You can now use the config prop to pass in crop mode. See #12
